chocAn: chocAn.cpp application.cpp manager.cpp provider.cpp member.cpp personal_info.cpp directory_list.cpp member_list.cpp provider_list.cpp service.cpp service_list.cpp procedure.cpp
	g++ -g -o chocAnExe.o chocAn.cpp application.cpp manager.cpp provider.cpp member.cpp personal_info.cpp directory_list.cpp member_list.cpp provider_list.cpp service.cpp service_list.cpp procedure.cpp -I.
